#!/usr/bin/env bash
FULL=`wc -c < map/map_full.scr.zx0`
NORTH=`wc -c < map/map_north.scr.zx0`
echo "#define MAP_BASE ((char *)&end_of_program)" > mapdata.h
echo "#define MAP_NORTH_BASE ((char *)(MAP_BASE+$FULL))" >> mapdata.h
echo "#define MAP_SOUTH_BASE ((char *)(MAP_BASE+$FULL+$NORTH))" >> mapdata.h
