name: Rolling Release
on: [push]
jobs:
  build-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get submodules
        run: |
            git submodule update --init bas2tap
            git submodule update --init bin2tap
            git submodule update --init ZX0
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y xonsh build-essential
            ./get_sdcc
            ./get_watcom
            sudo pip3 install -r requirements.txt
      - name: Build release files
        run: ./build_releases

      # okay, here's some shenanigans. Delete the release and the tag for it, then create the release tag again, then to the release

      - uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: Release
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: Release
          force_push_tag: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_archives/*
          tag_name: Release

