name: Rolling Release
on: [push]
jobs:
  build-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get submodules
        run: |
            git submodule update --init bas2tap
            git submodule update --init bin2tap
            git submodule update --init ZX0
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y xonsh build-essential
            ./get_sdcc
            ./get_watcom
            sudo pip3 install -r requirements.txt
      - name: Build release files
        run: ./build_releases
      - uses: actions/upload-artifact@v4
        with:
          name: EMFInfo_linux
          path: releases/linux
          if-no-files-found: error
          retention-days: 90
          overwrite: true
      - uses: actions/upload-artifact@v4
        with:
          name: EMFInfo_zxspectrum
          path: releases/zxspectrum
          if-no-files-found: error
          retention-days: 90
          overwrite: true
      - uses: actions/upload-artifact@v4
        with:
          name: EMFInfo_msdos
          path: releases/ms-dos
          if-no-files-found: error
          retention-days: 90
          overwrite: true
